Rebuild index.js on Dependabot PR.
ecmwf-actions/build-package pull request #58
Opened 2022-11-16 14:34 UTC by figi44

Adds a workflow to rebuild dist/index.js when Dependabot opens a pull request.

2022-11-16 14:34 UTC, FussyDuck commented
[![CLA assistant check](http://claassistant.ecmwf.int:80/pull/badge/not_signed)](http://claassistant.ecmwf.int:80/ecmwf-actions/build-package?pullRequest=58) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-actions/build-package?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-actions/build-package?pullRequest=58) it.</sub>

2022-11-16 14:54 UTC, dtip requested changes
This is a great start - reckon it needs a few tweaks before it'll be bulletproof!

2022-11-16 14:54 UTC, dtip commented on .github/workflows/dependabot-build.yml
> +        run: npm run lint-no-fix
Can probably skip this

2022-11-16 14:54 UTC, dtip commented on .github/workflows/dependabot-build.yml
> +          git checkout -b ${{github.head_ref}}
```suggestion
          git checkout -b ${{ github.head_ref }}
```
Idiomatic GitHub Actions YAML syntax typically has spaces around the expression in the curly brackets.

2022-11-16 14:58 UTC, dtip commented on .github/workflows/dependabot-build.yml
> +    if: github.actor == 'dependabot[bot]'
Might make more sense to use the `paths` filter to see if dependabot has changed `package.json`

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

2022-11-16 16:30 UTC, figi44 commented on .github/workflows/dependabot-build.yml
> +  pull_request:
`pull_request` should have enough permissions to push a commit, I tested it separately and it worked.

2022-11-17 08:33 UTC, dtip approved these changes
👍

2022-11-17 08:41 UTC, merged